In [2]:
# Python Program - Subtract Two Matrices

matrix1 = [[10, 11, 12],
          [13, 14, 15],
           [16, 17, 18]]
matrix2 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]
rmatrix = [[0, 0, 0],
           [0, 0, 0],
           [0, 0, 0]]
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        rmatrix[i][j] = matrix1[i][j] - matrix2[i][j]
for r in rmatrix:
    print(r)

[9, 9, 9]
[9, 9, 9]
[9, 9, 9]


In [3]:
# Python Program + Subtract Two Matrices

matrix1 = [[10, 11, 12],
          [13, 14, 15],
           [16, 17, 18]]
matrix2 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]
rmatrix = [[0, 0, 0],
           [0, 0, 0],
           [0, 0, 0]]
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        rmatrix[i][j] = matrix1[i][j] + matrix2[i][j]
for r in rmatrix:
    print(r)

[11, 13, 15]
[17, 19, 21]
[23, 25, 27]


In [ ]:
data= "Sandeep"
data[::-1]

In [ ]:
# Python Program - Make Simple Calculator

print("1. Addition");
print("2. Subtraction");
print("3. Multiplication");
print("4. Division");
print("5. Exit");
choice = int(input("Enter your choice: "));
if (choice>=1 and choice<=4):
    print("Enter two numbers: ");
    num1 = int(input());
    num2 = int(input());
    if choice == 1:
        res = num1 + num2;
        print("Result = ", res);
    elif choice == 2:
        res = num1 - num2;
        print("Result = ", res);
    elif choice == 3:
        res = num1 * num2;
        print("Result = ", res);
    else:
        res = num1 / num2;
        print("Result = ", res);
elif choice == 5:
    exit();
else:
    print("Wrong input..!!");

In [1]:
t=[1,2,3]*2

In [2]:
print(t)

[1, 2, 3, 1, 2, 3]


In [7]:
int(x)

NameError: name 'x' is not defined

In [10]:
a=[1,2,3,None,(),[]]
print((len(a)))

6


In [11]:
list1=[3,4,5,20,5]

In [12]:
list1.index(5)

2

In [13]:
random.randrange(3)

NameError: name 'random' is not defined

In [15]:
(3,1)
    

NameError: name 'CMP' is not defined

In [6]:
import numpy as np
l =[[1, 2, 3], [3, 6, 9], [2, 4, 6]]
c=np.array(l)
b=c[:,1]
print(b)

[2 6 4]


In [7]:
print(c[1, 1:3])

[6 9]


In [8]:
l =[[1, 2, 3], [3, 6, 9], [2, 4, 6]]
c=np.array(l)

In [9]:
c

array([[1, 2, 3],
       [3, 6, 9],
       [2, 4, 6]])

In [10]:
np.mat(l)

matrix([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])